### ISSUE TITLE
Instructions to build/deploy/test the editor in local environments

### ISSUE THREAD

**Issue by kYc0o** [kevoree/kevoree-web-editor#69]
While checking out old versions of the editor I realised that there's no actual "default way" to test the editor locally, and I didn't find any README or something similar with the instructions on how to test these older versions.

The instructions `npm install` and `grunt serve` work with latest versions, so I was figuring out if there's a possibility to include explicitly somewhere on a README or in the wiki pages of the project any instructions on how to test the older ones.

Besides that, I cannot find either any information about the dependencies needed from node.js, npm, etc. so I needed to follow a trial/error method to succeed a build.

Maybe this can be obvious for experts in the JavaScript world, but I think some guidelines would make this repo a bit more friendly for newbies like me.

**Comment by maxleiko** [comment]
As far as I remember I've always used Grunt as a task manager to handle the build/serving processes.  
This means that for any versions on that repo, the two (maybe three)  following commands should be enough to start a development version of the editor:

 - `npm install`
 - `bower install`
 - `grunt serve`

Also, versions prior to v5.x.y are really out-of-date and are no longer maintained so you will be on your own if anything breaks while issuing those commands :(  

I really encourages you to update your model loader/saver so that they comply to the new version of the meta-modal, you will save yourself a lot of troubles 👍

**Comment by kYc0o** [comment]
Thanks for your hints @maxleiko ! I'd like to comply with the latest version but I cannot do it mainly for two reasons:

1. The latest Kevoree meta-model it's bigger than the one I'm using, which was already limited for my application (kevoree on IoT low end devices ~32KB RAM).

2. The serialised JSON files are way too big to be transferred in Low Power an Lossy Networks (LLNs), which is the environment on which I'm working with this IoT devices.

Anyways, thanks for your suggestions, maybe I'll find a way to shrink the latest kevoree meta-model to comply with the new editor.
